version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /lookingGlass/containers/arr/gluetun:/gluetun
    env_file:
      - ./arr.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`gluetun.clean.barqu.xyz`)"
      - "traefik.http.routers.nginx.entrypoints=web"
    networks:
      - rprox

networks:
  rprox:
    external: true
