version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8090:8090 # qbittorrent
    volumes:
      - /lookingGlass/containers/arr/gluetun:/gluetun
    env_file:
      - ./arr.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`gluetun.clean.barqu.xyz`)"
      - "traefik.http.routers.nginx.entrypoints=web"
    networks:
      - rprox

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.rule=Host(`whoamivpn.clean.barqu.xyz`)"
    network_mode: "service:gluetun"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1001 #share
      - PGID=999 #docker
      - TZ=America/Chicago
    volumes:
      - /lookingGlass/containers/qbittorrent/config:/config
      - /zebra/share/qbittorrent/downloads:/data/downloads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gluetun-qbittorrent-rtr.entrypoints=web"
      - "traefik.http.routers.gluetun-qbittorrent-rtr.rule=Host(`qbit.clean.barqu.xyz`)" # qBittorrent
      ## Middlewares
#      - "traefik.http.routers.gluetun-qbittorrent-rtr.middlewares=chain-oauth@file" # qBittorrent
      ## HTTP Services
      - "traefik.http.routers.gluetun-qbittorrent-rtr.service=gluetun-svc" # qBittorrent
      - "traefik.http.services.gluetun-svc.loadbalancer.server.port=8080" # qBittorrent

networks:
  rprox:
    external: true
