services:
# GLUETUN
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
#      - 8090:8090/tcp # qbittorrent was 8090:8090
#      - 6881:6881 # qBittorrent listening port
#      - 9696:9696 # prowlarr
#      - 8989:8989 # sonarr TV
    volumes:
      - /home/zyzyx/lookingGlass/containers/arr/gluetun:/gluetun
    env_file:
      - ./arr.env
    labels:
      - "traefik.enable=true"
#      - "traefik.http.routers.nginx.rule=Host(`gluetun.clean.barqu.xyz`)"
      - "traefik.http.routers.nginx.entrypoints=web"
    networks:
      - rprox

# QBITTORRENT
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1001 #zebra
      - PGID=990 #docker
      - TZ=America/Chicago
    volumes:
      - /home/zyzyx/lookingGlass/containers/qbittorrent/config:/config
      - /home/zyzyx/lookingGlass/containers/qbittorrent/downloads:/data/downloads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gluetun-torrent.entrypoints=web"
      - "traefik.http.routers.gluetun-torrent.rule=Host(`torrent.clean.barqu.xyz`)"
      - "traefik.http.routers.gluetun-torrent.service=gluetun-torrent"
      - "traefik.http.services.gluetun-torrent.loadbalancer.server.port=8080"

networks:
  rprox:
    external: true
