---
version: "2.1"

services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1001 #share
      - PGID=999 #docker
      - TZ=America/Chicago
    #      - PASSWORD= #optional
    #      - CLI_ARGS= #optional
    volumes:
      - /zebra/share/Books2:/config
    ports:
      - 8080:8080
      - 8081:8081
      - 8181:8181

