version: "3"

services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1001 #share
      - PGID=999 #docker
      - TZ=America/Chicago
    #      - PASSWORD= #optional
    #      - CLI_ARGS= #optional
    volumes:
      - /zebra/share/Books:/config
    ports:
      - 8081:8081
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`books.clean.barqu.xyz`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.services.nginx.loadbalancer.server.port=8081"
    networks:
      - rprox

networks:
  rprox:
    external: true
