services:
  dns-server:
    container_name: dns-server
    hostname: dns-server-main
    image: technitium/dns-server:latest
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./config:/etc/dns
    environment:
      - DNS_SERVER_DOMAIN=${DNS_SERVER_DOMAIN}
      - TZ=${TZ}
      - DNS_SERVER_ADMIN_PASSWORD=${DNS_SERVER_ADMIN_PASSWORD}
