version: '3'

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
#    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "8080:8080"  # Don't do this in production!
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - rprox

networks:
  rprox:
    external: true
