---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /lookingGlass/containers/sonarr/config:/config
      - /zebra/share/Media/series:/tv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.clean.barqu.xyz`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
    networks:
      - rprox

networks:
  rprox:
      external: true
